### ISSUE TITLE
Does it work with strategy tester agents?

### ISSUE THREAD

**Issue by dseeker** [tickelton/docker-metatrader#1]
I tried making the MetaTester 5 Agents work on a Ubuntu 16.04 with Wine, and it does run, but the agents never connect anywhere, apparently like the Agents Manager cannot see the network interface.

Could you make them work properly with this docker container?

**Comment by tickelton** [comment]
Sorry I didn't reply earlier. Somehow I didn't get a notification from GitHub.

If you run the container with the argument "--net host" MetaTrader should have full network connectivity and behave as if it were run directly on the host.

**Comment by tickelton** [comment]
Closed due to inactivity.
