### ISSUE TITLE
 time zones in which they are located.

### ISSUE THREAD

**Issue by ulises2k** [tickelton/docker-metatrader#8]
Is it possible that I am not left wondering?
![image](https://user-images.githubusercontent.com/2415609/182735188-77b2ddff-77e9-4cca-a9c6-f913e8d7b562.png)

**Comment by shelomito12** [comment]
1. stop/kill the building process
2. delete this container
a) List all containers: `docker images -a`
b) if you are in a test environment and don't care about other containers, then delete all of them with: `docker system prune -a` 

then add `ENV DEBIAN_FRONTEND=noninteractive` to your Dockerfile:

```
...
# Base docker image.
FROM ubuntu:focal

ADD https://dl.winehq.org/wine-builds/winehq.key /winehq.key

# Fix time zone issue
ENV DEBIAN_FRONTEND=noninteractive

# Install Wine
...
```

re-run command: `docker build .`

**Comment by tickelton** [comment]
Fix was added to the Dockerfile.
